### ISSUE TITLE
Please add screenshots

### ISSUE THREAD

**Issue by cforce** [jzaiat/redshares#1]
Can i gibe right to roles to allow to give other user to edit or just view an item. Where can the user set this two allos for an issue? Is it possible ti mass aiign (issue list contect menu this two rights). Does the plugin take into account if users are

**Comment by jzaiat** [comment]
Hello, thanks for your interest in this plugin. 
I've added screenshots and further information and instructions on the readme file.
About your questions: 
- yes, you can give right to roles (the plugin is a module, see attached screenshot) 
- the user can add or remove shares from inside the issue (on the sidebar, just like watchers)
- no, right now the user can't mass assign nor use the context menu
- the last question is trimmed...

![redshare_permissions](https://f.cloud.github.com/assets/4991006/872246/eaf5d1b2-f85e-11e2-8a92-847ce9e3f3cc.png

Let me know if you have another question.
Thanks
Jonathan
