### ISSUE TITLE
Internal error when trying to configure plugin

### ISSUE THREAD

**Issue by nimuytan** [jzaiat/redshares#2]
Completed 500 Internal Server Error in 4ms

NoMethodError (undefined method `plugin_redshares' for #<Class:0xa667f24>):
  app/controllers/settings_controller.rb:68:in`plugin'

![image](https://f.cloud.github.com/assets/5049433/1052431/2fca85c6-10dd-11e3-8bb5-07901839ce06.png)

**Comment by nimuytan** [comment]
Finally I found out what the problem was...
It was  an incompatibility with one plugin --> http://www.redmine.org/plugins/wk-time in the version 1.5
Luckly the last version of this plugin (1.6) work fine too with redshares. So problem resolved.

**Comment by pengux** [comment]
I don't have that plugin but still getting the same error. Which part caused incompatibility?
